# Load libraries

In [235]:
import pandas as pd
import numpy as np
from scipy import stats

# Reading the file

In [236]:
#df=pd.read_csv('../data/raw/glassdoor_reviews.csv')
#df.head()

# Checking null values, shape and types

In [237]:
#df.shape

In [238]:
#df_na = df[:].isnull().sum()
#df_na

In [239]:
#df.dtypes

In [240]:
#df['year'] = df['date_review'].str[:4]
#df.head()

In [241]:
#df1 = df['year'].value_counts()
#df1.head()

I decided to use only 4 years, 2 from before the pandemic and 2 during (2018,2019,2020 and 2021)

In [242]:
#year_used=['2018','2019','2020','2021']
#filtered_df=df[df['year'].isin(year_used)]
#filtered_df

In [243]:
#filtered_df.to_csv('filtered_df.csv', index=False)

# Using the filtered dataset

In [244]:
df=pd.read_csv('../data/raw/filtered_df.csv')
df

firm date_review                         job_title  \
0       AFH-Wealth-Management  2018-01-29                Anonymous Employee   
1       AFH-Wealth-Management  2018-07-05                Anonymous Employee   
2       AFH-Wealth-Management  2018-08-02                Anonymous Employee   
3       AFH-Wealth-Management  2018-09-07                Anonymous Employee   
4       AFH-Wealth-Management  2018-12-04                Anonymous Employee   
...                       ...         ...                               ...   
476125         the-LEGO-Group  2021-06-02                 Marketing Manager   
476126         the-LEGO-Group  2021-06-03                   Sales Associate   
476127         the-LEGO-Group  2021-06-03                        Strategist   
476128         the-LEGO-Group  2021-06-04   Customer Service Representative   
476129         the-LEGO-Group  2021-06-04        Human Resources Specialist   

                                    current  \
0                          Current Employee   
1        Former Employee, more than 3 years   
2       Current Employee, more than 3 years   
3                          Current Employee   
4                           Former Employee   
...                                     ...   
476125  Current Employee, more than 5 years   
476126   Current Employee, less than 1 year   
476127                     Current Employee   
476128   Current Employee, less than 1 year   
476129  Current Employee, more than 3 years   

                                          location  overall_rating  \
0                                              NaN               5   
1                                              NaN               1   
2                                              NaN               5   
3                                              NaN               4   
4                                              NaN               2   
...                                            ...             ...   
476125                   München, Bavaria, Bavaria               5   
476126                    London, England, England               3   
476127                                         NaN               4   
476128                                         NaN               5   
476129  Kladno, Central Bohemian, Central Bohemian               5   

        work_life_balance  culture_values  diversity_inclusion  career_opp  \
0                     5.0             5.0                  NaN         5.0   
1                     3.0             1.0                  NaN         2.0   
2                     5.0             5.0                  NaN         4.0   
3                     3.0             3.0                  NaN         5.0   
4                     4.0             2.0                  NaN         2.0   
...                   ...             ...                  ...         ...   
476125                4.0             5.0                  4.0         4.0   
476126                NaN             NaN                  NaN         NaN   
476127                5.0             5.0                  5.0         3.0   
476128                NaN             NaN                  NaN         NaN   
476129                4.0             5.0                  4.0         4.0   

        comp_benefits  senior_mgmt recommend ceo_approv outlook  \
0                 5.0          5.0         v          o       v   
1                 1.0          1.0         x          x       v   
2                 4.0          4.0         v          o       v   
3                 2.0          3.0         v          v       v   
4                 1.0          1.0         x          o       o   
...               ...          ...       ...        ...     ...   
476125            4.0          4.0         v          v       v   
476126            NaN          NaN         o          o       o   
476127            5.0          3.0         v          o       o   
476128            NaN          NaN         o          o       o

In [245]:
df.shape

(476130, 19)

In [246]:
df.dtypes

firm                    object
date_review             object
job_title               object
current                 object
location                object
overall_rating           int64
work_life_balance      float64
culture_values         float64
diversity_inclusion    float64
career_opp             float64
comp_benefits          float64
senior_mgmt            float64
recommend               object
ceo_approv              object
outlook                 object
headline                object
pros                    object
cons                    object
year                     int64
dtype: object

In [247]:
df[:].isnull().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location               156491
overall_rating              0
work_life_balance      110435
culture_values         111633
diversity_inclusion    340064
career_opp             108303
comp_benefits          110308
senior_mgmt            113442
recommend                   0
ceo_approv                  0
outlook                     0
headline                 1883
pros                        0
cons                        4
year                        0
dtype: int64

ceo_approv info: 
v - Positive, r - Mild, x - Negative, o - No opinion

In [248]:
df['ceo_approv'].unique()

array(['o', 'x', 'v', 'r'], dtype=object)

In [249]:
df['career_opp'].unique()

array([ 5.,  2.,  4.,  3.,  1., nan])

In [250]:
df['senior_mgmt'].unique()

array([ 5.,  1.,  4.,  3., nan,  2.])

In [251]:
df['comp_benefits'].unique()

array([ 5.,  1.,  4.,  2.,  3., nan])

In [252]:
df['diversity_inclusion'].unique()

array([nan,  1.,  2.,  4.,  5.,  3.])

In [253]:
df['diversity_inclusion'].value_counts()

5.0    60422
4.0    36101
3.0    22574
2.0     8516
1.0     8453
Name: diversity_inclusion, dtype: int64

In [254]:
#df['diversity_inclusion'].replace(to_replace="year",
 #          value=np.nan)

In [255]:
df1=df[df['year'] < 2020]

In [256]:
df['firm'].unique()

array(['AFH-Wealth-Management', 'AJ-Bell', 'ALDI', 'AQA', 'ASDA', 'ASOS',
       'AXA-UK', 'Abcam',
       'Abertawe-Bro-Morgannwg-University-Health-Board', 'Accenture',
       'Accor', 'Achieving-for-Children', 'ActionCOACH',
       'Active-Care-Group', 'Adecco', 'Age-UK-The-National-Charity',
       'AlixPartners', 'American-Express', 'Amey', 'Angard-Staffing',
       'Anglian-Water', 'Anglo-American',
       'Animal-and-Plant-Health-Agency', 'Aon', 'Apple', 'Arcadia',
       'Arnold-Clark', 'AstraZeneca', 'Aviva', 'B-and-M-Retail',
       'B-and-Q', 'BAT', 'BBC', 'BDO', 'BHS', 'BIS', 'BNP-Paribas',
       'BNY-Mellon', 'BP', 'BPP-Holdings', 'BT',
       'Babcock-International-Group', 'Babylon-Health',
       'Bain-and-Company', 'Balfour-Beatty', 'Bannatyne-Group',
       'Barchester-Healthcare', 'Barclays', 'Barnardo-s',
       'Barnet-and-Chase-Farm-Hospitals-NHS-Trust', 'Barnett-Waddingham',
       'Barratt-Developments', 'Barts-Health-NHS-Trust',
       'BayWa-r-e-renewable-energ

In [257]:
df1.shape

(191242, 19)

In [258]:
df1[:].isnull().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location                86961
overall_rating              0
work_life_balance       30529
culture_values          31768
diversity_inclusion    191242
career_opp              30345
comp_benefits           30869
senior_mgmt             32382
recommend                   0
ceo_approv                  0
outlook                     0
headline                  240
pros                        0
cons                        3
year                        0
dtype: int64

In [259]:
df1["location"]=df1["location"].fillna("No location")

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\1190422171.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["location"]=df1["location"].fillna("No location")


In [260]:
df1[:].isnull().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location                    0
overall_rating              0
work_life_balance       30529
culture_values          31768
diversity_inclusion    191242
career_opp              30345
comp_benefits           30869
senior_mgmt             32382
recommend                   0
ceo_approv                  0
outlook                     0
headline                  240
pros                        0
cons                        3
year                        0
dtype: int64

Taking mode by company and storing in dictionary df1

In [261]:
wlb=df1.groupby('firm')['work_life_balance'].agg(lambda x: pd.Series.mode(x)[0])
wlb

firm
AFH-Wealth-Management    5.0
AJ-Bell                  5.0
ALDI                     1.0
AQA                      4.0
ASDA                     3.0
                        ... 
i-Net-Solution           5.0
ibis                     3.0
mydentist-UK             4.0
next                     3.0
the-LEGO-Group           5.0
Name: work_life_balance, Length: 423, dtype: float64

In [262]:
dictwlb = wlb.to_dict()

In [263]:
cv=df1.groupby('firm')['culture_values'].agg(lambda x: pd.Series.mode(x)[0])

In [264]:
dictcv = cv.to_dict()

In [265]:
co=df1.groupby('firm')['career_opp'].agg(lambda x: pd.Series.mode(x)[0])

In [266]:
dictco = co.to_dict()

In [324]:
cb=df1.groupby('firm')['comp_benefits'].agg(lambda x: pd.Series.mode(x)[0])

In [325]:
dictcb = cb.to_dict()

In [269]:
sm1=df1.groupby('firm')['senior_mgmt'].agg(lambda x: pd.Series.mode(x)[0])

In [270]:
dictsm1 = sm1.to_dict()

In [271]:
df1[:].isnull().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location                    0
overall_rating              0
work_life_balance       30529
culture_values          31768
diversity_inclusion    191242
career_opp              30345
comp_benefits           30869
senior_mgmt             32382
recommend                   0
ceo_approv                  0
outlook                     0
headline                  240
pros                        0
cons                        3
year                        0
dtype: int64

now df2

In [272]:
df2=df[df['year'] >= 2020]

In [273]:
df2.shape

(284888, 19)

In [274]:
df2[:].isnull().sum()

firm                        0
date_review                 0
job_title                   0
current                     0
location                69530
overall_rating              0
work_life_balance       79906
culture_values          79865
diversity_inclusion    148822
career_opp              77958
comp_benefits           79439
senior_mgmt             81060
recommend                   0
ceo_approv                  0
outlook                     0
headline                 1643
pros                        0
cons                        1
year                        0
dtype: int64

In [275]:
df2["location"]=df2["location"].fillna("No location")

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\3121176922.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["location"]=df2["location"].fillna("No location")


Taking mode by company and storing in dictionary df2

In [276]:
wlb2=df2.groupby('firm')['work_life_balance'].agg(lambda x: pd.Series.mode(x)[0])
wlb2

firm
AFH-Wealth-Management      5.0
AJ-Bell                    5.0
ALDI                       1.0
AQA                        5.0
ASDA                       3.0
                          ... 
YOOX-NET-A-PORTER-GROUP    4.0
ibis                       3.0
mydentist-UK               1.0
next                       4.0
the-LEGO-Group             5.0
Name: work_life_balance, Length: 426, dtype: float64

In [277]:
dictwlb2 = wlb2.to_dict()


In [278]:
cv2=df2.groupby('firm')['culture_values'].agg(lambda x: pd.Series.mode(x)[0])

In [279]:
dictcv2 = cv2.to_dict()

In [280]:
co2=df2.groupby('firm')['career_opp'].agg(lambda x: pd.Series.mode(x)[0])

In [281]:
dictco2 = co2.to_dict()

In [326]:
cb2=df2.groupby('firm')['comp_benefits'].agg(lambda x: pd.Series.mode(x)[0])

In [327]:
dictcb2 = cb2.to_dict()

In [284]:
sm2=df.groupby('firm')['senior_mgmt'].agg(lambda x: pd.Series.mode(x)[0])

In [285]:
dictsm2 = sm2.to_dict()

fill na values with mode by companies for df1

In [286]:
df1.work_life_balance = df1.work_life_balance.fillna(df.firm.map(dictwlb))
#df1.loc[df1['work_life_balance'].isnull(), ['firm','work_life_balance']].head()
#df1.loc[df1['work_life_balance'].isnull(), 'work_life_balance'] = df1['firm'].map(dictwlb)

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\4042385781.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.work_life_balance = df1.work_life_balance.fillna(df.firm.map(dictwlb))


In [287]:
df1['work_life_balance'].unique()

array([5., 3., 4., 2., 1.])

In [288]:
df1.culture_values = df1.culture_values.fillna(df.firm.map(dictcv))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\767004147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.culture_values = df1.culture_values.fillna(df.firm.map(dictcv))


In [289]:
df1.work_life_balance = df1.work_life_balance.fillna(df.firm.map(dictwlb))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\1870202089.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.work_life_balance = df1.work_life_balance.fillna(df.firm.map(dictwlb))


In [328]:
df1.comp_benefits = df1.comp_benefits.fillna(df.firm.map(dictcb))

In [329]:
df1.loc[df1['career_opp'].isnull(), 'career_opp'] = df1['firm'].map(dictco)

In [330]:
df1.loc[df1['senior_mgmt'].isnull(), 'senior_mgmt'] = df1['firm'].map(dictsm1)

In [331]:
df1[:].isnull().sum()

firm                     0
date_review              0
job_title                0
current                  0
location                 0
overall_rating           0
work_life_balance        0
culture_values           0
diversity_inclusion      0
career_opp               0
comp_benefits            0
senior_mgmt              0
recommend                0
ceo_approv               0
outlook                  0
headline               240
pros                     0
cons                     3
year                     0
dtype: int64

fill na values with mode by companies df2

In [332]:
df2.work_life_balance = df2.work_life_balance.fillna(df.firm.map(dictwlb2))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\2071172852.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.work_life_balance = df2.work_life_balance.fillna(df.firm.map(dictwlb2))


In [333]:
df2.culture_values = df2.culture_values.fillna(df.firm.map(dictcv2))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\737880384.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.culture_values = df2.culture_values.fillna(df.firm.map(dictcv2))


In [334]:
df2.career_opp = df2.career_opp.fillna(df.firm.map(dictco2))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\745469023.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.career_opp = df2.career_opp.fillna(df.firm.map(dictco2))


In [335]:
df2.comp_benefits = df2.comp_benefits.fillna(df.firm.map(dictco2))

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\375969365.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.comp_benefits = df2.comp_benefits.fillna(df.firm.map(dictco2))


In [336]:
df2.loc[df2['senior_mgmt'].isnull(), 'senior_mgmt'] = df2['firm'].map(dictsm2)

In [337]:
df2[:].isnull().sum()

firm                      0
date_review               0
job_title                 0
current                   0
location                  0
overall_rating            0
work_life_balance         0
culture_values            0
diversity_inclusion       0
career_opp                0
comp_benefits             0
senior_mgmt               0
recommend                 0
ceo_approv                0
outlook                   0
headline               1643
pros                      0
cons                      1
year                      0
dtype: int64

In [344]:
df1['diversity_inclusion'].unique()

array([1., 5., 4., 3., 0., 2.])

In [339]:
df1['diversity_inclusion'].unique()

array([1., 5., 4., 3., 0., 2.])

In [341]:
df2['diversity_inclusion'].unique()

array([1., 2., 4., 5., 3., 0.])

In [343]:
df2['diversity_inclusion'].value_counts()

5.0    204843
4.0     39278
3.0     23283
1.0      8919
2.0      8563
0.0         2
Name: diversity_inclusion, dtype: int64

In [345]:
df2.head()

firm date_review                   job_title  \
19  AFH-Wealth-Management  2020-01-07              Administrative   
20  AFH-Wealth-Management  2020-01-20               Administrator   
21  AFH-Wealth-Management  2020-02-20              Administrative   
22  AFH-Wealth-Management  2020-02-29   Member Of Technical Staff   
23  AFH-Wealth-Management  2020-06-05         Back Office Support   

                                current                      location  \
19                      Former Employee                   No location   
20  Current Employee, more than 3 years  Bromsgrove, England, England   
21                     Current Employee                   No location   
22   Current Employee, more than 1 year                   No location   
23  Current Employee, more than 3 years  Bromsgrove, England, England   

    overall_rating  work_life_balance  culture_values  diversity_inclusion  \
19               1                5.0             5.0                  1.0   
20               5                5.0             5.0                  1.0   
21               5                5.0             5.0                  1.0   
22               2                3.0             2.0                  1.0   
23               2                5.0             5.0                  1.0   

    career_opp  comp_benefits  senior_mgmt recommend ceo_approv outlook  \
19         1.0            1.0          1.0         x          o       o   
20         5.0            5.0          2.0         v          o       v   
21         5.0            5.0          4.0         v          o       v   
22         2.0            1.0          1.0         x          v       x   
23         1.0            1.0          1.0         o          o       o   

                                             headline  \
19         The most demoralising job I have ever had.   
20                               Great Place to Work!   
21                                   Great to work at   
22  Self centred business with poor focus on genui...   
23  A mixed bag, but on balance more negative than...   

                                                 pros  \
19                  Staff events throughout the year.   
20  Approachable staff\r\nClient focused\r\nStaff ...   
21  Friendly people, genuine attempts to engage an...   
22  Some genuinely nice people do work here with s...   
23  A growing and profitable company.\r\nFlexible ...   

                                                 cons  year  
19  One particular department lets the whole compa...  2020  
20  Salary for administration staff needs to be lo...  2020  
21  Tiny bit old fashioned in certain ways I.e. dr...  2020  
22  Too many 'vanity projects' and self promoting ...  2020  
23  Autocratic, very much a “my way or the highway...  2020

In [346]:

stats.mode(df2[df2['diversity_inclusion'].isna()==False]['diversity_inclusion'],nan_policy="omit", keepdims=True)[0][0]

5.0

In [347]:
dictdi2=df2.groupby(['firm'])['diversity_inclusion'].agg(lambda x: stats.mode(x,nan_policy="omit",keepdims=True)[0][0])

In [348]:
dictdi2

firm
AFH-Wealth-Management      1.0
AJ-Bell                    1.0
ALDI                       5.0
AQA                        4.0
ASDA                       5.0
                          ... 
YOOX-NET-A-PORTER-GROUP    4.0
ibis                       5.0
mydentist-UK               1.0
next                       5.0
the-LEGO-Group             5.0
Name: diversity_inclusion, Length: 426, dtype: float64

In [349]:
df2.loc[df2['diversity_inclusion'].isnull(), 'diversity_inclusion'] = df2['firm'].map(dictdi2)

In [350]:
df2[:].isnull().sum()

firm                      0
date_review               0
job_title                 0
current                   0
location                  0
overall_rating            0
work_life_balance         0
culture_values            0
diversity_inclusion       0
career_opp                0
comp_benefits             0
senior_mgmt               0
recommend                 0
ceo_approv                0
outlook                   0
headline               1643
pros                      0
cons                      1
year                      0
dtype: int64

Since in df1 we didn´t had values for diversity inclusion I used the mode from df2 and will drop the rows that still have null values (only 2)

In [352]:
df1.loc[df1['diversity_inclusion'].isnull(), 'diversity_inclusion'] = df1['firm'].map(dictdi2)

In [353]:
df1[:].isnull().sum()

firm                     0
date_review              0
job_title                0
current                  0
location                 0
overall_rating           0
work_life_balance        0
culture_values           0
diversity_inclusion      0
career_opp               0
comp_benefits            0
senior_mgmt              0
recommend                0
ceo_approv               0
outlook                  0
headline               240
pros                     0
cons                     3
year                     0
dtype: int64

In [354]:
df1 = df1.dropna(subset=['diversity_inclusion'])

In [355]:
df1[:].isnull().sum()

firm                     0
date_review              0
job_title                0
current                  0
location                 0
overall_rating           0
work_life_balance        0
culture_values           0
diversity_inclusion      0
career_opp               0
comp_benefits            0
senior_mgmt              0
recommend                0
ceo_approv               0
outlook                  0
headline               240
pros                     0
cons                     3
year                     0
dtype: int64

In [365]:
df2['work_life_balance'].unique()

array([5., 3., 1., 4., 2.])

Concatenating  

In [375]:

df_merged = df1.append(df2, ignore_index=True)

C:\Users\pbevi\AppData\Local\Temp\ipykernel_5716\3008251476.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_merged = df1.append(df2, ignore_index=True)


In [376]:
df_merged

firm date_review                         job_title  \
0       AFH-Wealth-Management  2018-01-29                Anonymous Employee   
1       AFH-Wealth-Management  2018-07-05                Anonymous Employee   
2       AFH-Wealth-Management  2018-08-02                Anonymous Employee   
3       AFH-Wealth-Management  2018-09-07                Anonymous Employee   
4       AFH-Wealth-Management  2018-12-04                Anonymous Employee   
...                       ...         ...                               ...   
476123         the-LEGO-Group  2021-06-02                 Marketing Manager   
476124         the-LEGO-Group  2021-06-03                   Sales Associate   
476125         the-LEGO-Group  2021-06-03                        Strategist   
476126         the-LEGO-Group  2021-06-04   Customer Service Representative   
476127         the-LEGO-Group  2021-06-04        Human Resources Specialist   

                                    current  \
0                          Current Employee   
1        Former Employee, more than 3 years   
2       Current Employee, more than 3 years   
3                          Current Employee   
4                           Former Employee   
...                                     ...   
476123  Current Employee, more than 5 years   
476124   Current Employee, less than 1 year   
476125                     Current Employee   
476126   Current Employee, less than 1 year   
476127  Current Employee, more than 3 years   

                                          location  overall_rating  \
0                                      No location               5   
1                                      No location               1   
2                                      No location               5   
3                                      No location               4   
4                                      No location               2   
...                                            ...             ...   
476123                   München, Bavaria, Bavaria               5   
476124                    London, England, England               3   
476125                                 No location               4   
476126                                 No location               5   
476127  Kladno, Central Bohemian, Central Bohemian               5   

        work_life_balance  culture_values  diversity_inclusion  career_opp  \
0                     5.0             5.0                  1.0         5.0   
1                     3.0             1.0                  1.0         2.0   
2                     5.0             5.0                  1.0         4.0   
3                     3.0             3.0                  1.0         5.0   
4                     4.0             2.0                  1.0         2.0   
...                   ...             ...                  ...         ...   
476123                4.0             5.0                  4.0         4.0   
476124                5.0             5.0                  5.0         5.0   
476125                5.0             5.0                  5.0         3.0   
476126                5.0             5.0                  5.0         5.0   
476127                4.0             5.0                  4.0         4.0   

        comp_benefits  senior_mgmt recommend ceo_approv outlook  \
0                 5.0          5.0         v          o       v   
1                 1.0          1.0         x          x       v   
2                 4.0          4.0         v          o       v   
3                 2.0          3.0         v          v       v   
4                 1.0          1.0         x          o       o   
...               ...          ...       ...        ...     ...   
476123            4.0          4.0         v          v       v   
476124            5.0          5.0         o          o       o   
476125            5.0          3.0         v          o       o   
476126            5.0          5.0         o          o       o

In [377]:
df_merged.to_csv('cleaned_df.csv', index=False)

In [380]:
df_merged['work_life_balance'].unique()

array([5., 3., 4., 2., 1.])

In [382]:
df_merged.to_csv('cleaned_df2.csv', index=False)

In [384]:
data=pd.read_csv('../data/clean/cleaned_df2.csv')
data.head()

firm date_review            job_title  \
0  AFH-Wealth-Management  2018-01-29   Anonymous Employee   
1  AFH-Wealth-Management  2018-07-05   Anonymous Employee   
2  AFH-Wealth-Management  2018-08-02   Anonymous Employee   
3  AFH-Wealth-Management  2018-09-07   Anonymous Employee   
4  AFH-Wealth-Management  2018-12-04   Anonymous Employee   

                               current     location  overall_rating  \
0                     Current Employee  No location               5   
1   Former Employee, more than 3 years  No location               1   
2  Current Employee, more than 3 years  No location               5   
3                     Current Employee  No location               4   
4                      Former Employee  No location               2   

   work_life_balance  culture_values  diversity_inclusion  career_opp  \
0                5.0             5.0                  1.0         5.0   
1                3.0             1.0                  1.0         2.0   
2                5.0             5.0                  1.0         4.0   
3                3.0             3.0                  1.0         5.0   
4                4.0             2.0                  1.0         2.0   

   comp_benefits  senior_mgmt recommend ceo_approv outlook  \
0            5.0          5.0         v          o       v   
1            1.0          1.0         x          x       v   
2            4.0          4.0         v          o       v   
3            2.0          3.0         v          v       v   
4            1.0          1.0         x          o       o   

                                            headline  \
0                                     Administration   
1                            Could be so much better   
2                                 Employer of choice   
3                                 Good place to work   
4  In the process of trying to provide the best s...   

                                                pros  \
0  Really nice community, lots of benefits for em...   
1  Lots of talented and friendly people.\r\n\r\nR...   
2  Top CEO with a vision and desire to make thing...   
3  Very professional manner and lots of opportuni...   
4  The compressed hours structure works well wher...   

                                                cons  year  
0   nothing that i can think of- i love working here  2018  
1  The talented and friendly people are woefully ...  2018  
2           There are none... it's what you make it.  2018  
3                        There are none to point out  2018  
4  I genuinely believe AFH have a good offering f...  2018

In [385]:
data.dtypes

firm                    object
date_review             object
job_title               object
current                 object
location                object
overall_rating           int64
work_life_balance      float64
culture_values         float64
diversity_inclusion    float64
career_opp             float64
comp_benefits          float64
senior_mgmt            float64
recommend               object
ceo_approv              object
outlook                 object
headline                object
pros                    object
cons                    object
year                     int64
dtype: object

In [386]:
data[:].isnull().sum()

firm                      0
date_review               0
job_title                 0
current                   0
location                  0
overall_rating            0
work_life_balance         0
culture_values            0
diversity_inclusion       0
career_opp                0
comp_benefits             0
senior_mgmt               0
recommend                 0
ceo_approv                0
outlook                   0
headline               1883
pros                      0
cons                      4
year                      0
dtype: int64

In [387]:
data['job_title'].value_counts()

 Anonymous Employee               83700
 Manager                           9962
 Consultant                        8350
                                   7963
 Software Engineer                 7234
                                  ...  
 Games Salesperson                    1
 Ul Developer                         1
 Senior Softwared Developer           1
 Product Operations Specialist        1
 Senior Experience Designer           1
Name: job_title, Length: 42460, dtype: int64

In [388]:
data['location'].value_counts()

No location                 156489
London, England, England     39549
Bangalore                    17494
New York, NY                 13911
Hyderābād                     7230
                             ...  
Fort Carson, CO                  1
Fort Gordon, GA                  1
Bost, Flemish Brabant            1
Toano, VA                        1
Wijnegem, Antwerp                1
Name: location, Length: 11045, dtype: int64

In [389]:
data['work_life_balance'].unique()

array([5., 3., 4., 2., 1.])